### ISSUE TITLE
Flagging typos

### ISSUE THREAD

**Issue by BaxxiJ** [VML/journey-driven-development#11]
In reading the Doc (pdf) I found some typos so I thought I'd flag them in an issue rather than submit a PR as per the contributing guidelines, here's a summary and I've already forked and committed all the changes if you'd like me to raise a PR

**In section 1.4 (preface, front matter)** 

the word "paring" is used instead of "pairing"

> All code has at least a cursory peer review before commit.
> This arises naturally during **paring**, but can happen otherwise.

**In part 2 (process) the penultimate paragraph has the sentence:** 

> The promise of Agile development practices is hampered or lost when traditional
> by following traditional application deployment and delivery techniques.

which looks partly through an edit I would change to:
"The promise of Agile development practices is hampered or lost when following traditional application deployment and delivery techniques."

**In section 6.1 (DevOps) I found a potential plural issue:** 

> Physical manufacturing turns raw materials into finished goods for sale. The
> raw materials for software are business **hypothesis** resulting from insights into
> customer journeys.

I would presume that this should be the plural "hypotheses" due to the pluralisation on "materials" and "are"

**In Chapter 16 (agile release planning) section 1.2 a space was needed between two words:**

> Another thing we do is **plotthe** distribution, or the number of stories in each
> category to evaluate the distribution of stories.

**Comment by davidmitchell** [comment]
got all of these in yesterday and ran a new build. 

Sorry took so long for me to notice this issue!

Thanks for reading and the feedback!
